2025-06-09 01:25:37,194 - log_util.py[DEBUG]: Cloud-init v. 25.1.1-0ubuntu2 running 'init-local' at Mon, 09 Jun 2025 01:25:37 +0000. Up 4.86 seconds.
2025-06-09 01:25:37,194 - main.py[INFO]: PID [1] started cloud-init 'init-local'.
2025-06-09 01:25:37,194 - main.py[DEBUG]: No kernel command line url found.
2025-06-09 01:25:37,194 - main.py[DEBUG]: Closing stdin
2025-06-09 01:25:37,198 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2025-06-09 01:25:37,199 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 101:4
2025-06-09 01:25:37,199 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 4 bytes
2025-06-09 01:25:37,199 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
2025-06-09 01:25:37,199 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
2025-06-09 01:25:37,199 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-06-09 01:25:37,199 - stages.py[DEBUG]: no cache found
2025-06-09 01:25:37,199 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
2025-06-09 01:25:37,205 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-06-09 01:25:37,206 - sources[DEBUG]: Looking for data source in: ['None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
2025-06-09 01:25:37,212 - sources[DEBUG]: Searching for local data source in: []
2025-06-09 01:25:37,212 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-06-09 01:25:37,212 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-06-09 01:25:37,212 - main.py[DEBUG]: No local datasource found
2025-06-09 01:25:37,218 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2025-06-09 01:25:37,219 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enp0s8/address
2025-06-09 01:25:37,219 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-06-09 01:25:37,219 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-06-09 01:25:37,219 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2025-06-09 01:25:37,219 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enp0s8/address
2025-06-09 01:25:37,219 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-06-09 01:25:37,219 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-06-09 01:25:37,219 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-network-config-v2.json (quiet=False)
2025-06-09 01:25:37,226 - util.py[DEBUG]: Reading 17906 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-network-config-v2.json
2025-06-09 01:25:37,227 - schema.py[DEBUG]: Validating network-config with netplan API
2025-06-09 01:25:37,228 - util.py[DEBUG]: Writing to /run/cloud-init/tmp/tmpsdiwbno3/etc/netplan/network-config.yaml - wb: [600] 87 bytes
2025-06-09 01:25:37,234 - performance.py[DEBUG]: Validating schema took 0.012 seconds
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/addr_assign_type (quiet=False)
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enp0s8/addr_assign_type
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/uevent (quiet=False)
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading 27 bytes from /sys/class/net/enp0s8/uevent
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enp0s8/address
2025-06-09 01:25:37,234 - net[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/device/device (quiet=False)
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading 7 bytes from /sys/class/net/enp0s8/device/device
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/lo/addr_assign_type
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading 23 bytes from /sys/class/net/lo/uevent
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/type (quiet=False)
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enp0s8/type
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-06-09 01:25:37,234 - util.py[DEBUG]: Reading 4 bytes from /sys/class/net/lo/type
2025-06-09 01:25:37,234 - networking.py[DEBUG]: net: all expected physical devices present
2025-06-09 01:25:37,234 - stages.py[DEBUG]: applying net config names for {'ethernets': {'enp0s8': {'dhcp4': True}}, 'version': 2}
2025-06-09 01:25:37,234 - net[DEBUG]: no interfaces to rename
2025-06-09 01:25:37,234 - stages.py[INFO]: Applying network configuration from system_cfg bringup=False: {'ethernets': {'enp0s8': {'dhcp4': True}}, 'version': 2}
2025-06-09 01:25:37,235 - util.py[DEBUG]: Writing to /run/cloud-init/sem/apply_network_config.once - wb: [644] 24 bytes
2025-06-09 01:25:37,240 - distros[DEBUG]: Selected renderer 'netplan' from priority list: ['netplan', 'eni', 'sysconfig']
2025-06-09 01:25:37,240 - network_state.py[DEBUG]: Passthrough netplan v2 config
2025-06-09 01:25:37,241 - netplan.py[DEBUG]: V2 to V2 passthrough
2025-06-09 01:25:37,243 - netplan.py[DEBUG]: Rendered netplan config using netplan python API
2025-06-09 01:25:37,243 - subp.py[DEBUG]: Running command ['netplan', 'generate'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:37,879 - performance.py[DEBUG]: Running ['netplan', 'generate'] took 0.637 seconds
2025-06-09 01:25:37,879 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/enp0s8'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:37,883 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/lo'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:37,886 - distros[DEBUG]: Not bringing up newly configured network interfaces
2025-06-09 01:25:37,886 - main.py[DEBUG]: [local] Exiting without datasource
2025-06-09 01:25:37,886 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-09 01:25:37,886 - util.py[DEBUG]: Reading 11 bytes from /proc/uptime
2025-06-09 01:25:37,886 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpot38yp0k) - w: [644] 482 bytes/chars
2025-06-09 01:25:37,887 - performance.py[DEBUG]: cloud-init stage: 'init-local' took 0.781 seconds
2025-06-09 01:25:37,887 - handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
2025-06-09 01:25:37,887 - socket.py[INFO]: Sending sd_notify(STATUS=Waiting on external services to complete before starting the network stage.)
2025-06-09 01:25:44,540 - performance.py[DEBUG]: Waiting to start stage network took 6.653 seconds
2025-06-09 01:25:44,540 - socket.py[INFO]: Sending sd_notify(STATUS=Running (network stage))
2025-06-09 01:25:44,540 - signal_handler.py[INFO]: Signal state [<function _handle_exit at 0xebd818c44860>] - previously custom handler.
2025-06-09 01:25:44,540 - signal_handler.py[INFO]: Signal state [<function _handle_exit at 0xebd818c44860>] - previously custom handler.
2025-06-09 01:25:44,540 - signal_handler.py[INFO]: Signal state [<function _handle_exit at 0xebd818c44860>] - previously custom handler.
2025-06-09 01:25:44,540 - handlers.py[DEBUG]: start: init-network: searching for network datasources
2025-06-09 01:25:44,540 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-09 01:25:44,540 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-06-09 01:25:44,540 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,545 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2025-06-09 01:25:44,545 - util.py[DEBUG]: Reading 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2025-06-09 01:25:44,545 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,546 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2025-06-09 01:25:44,546 - util.py[DEBUG]: Reading 811 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2025-06-09 01:25:44,546 - util.py[DEBUG]: Attempting to load yaml from string of length 811 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,547 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-06-09 01:25:44,547 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-06-09 01:25:44,547 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,548 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-installer-network.cfg (quiet=False)
2025-06-09 01:25:44,548 - util.py[DEBUG]: Reading 117 bytes from /etc/cloud/cloud.cfg.d/90-installer-network.cfg
2025-06-09 01:25:44,548 - util.py[DEBUG]: Attempting to load yaml from string of length 117 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,548 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg (quiet=False)
2025-06-09 01:25:44,550 - util.py[DEBUG]: Reading 28 bytes from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg
2025-06-09 01:25:44,550 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,551 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-09 01:25:44,551 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-09 01:25:44,551 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,552 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-09 01:25:44,552 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,552 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-09 01:25:44,552 - util.py[DEBUG]: Reading from /var/lib/cloud/data/status.json (quiet=False)
2025-06-09 01:25:44,552 - util.py[DEBUG]: Reading 482 bytes from /var/lib/cloud/data/status.json
2025-06-09 01:25:44,552 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-09 01:25:44,552 - util.py[DEBUG]: Reading 12 bytes from /proc/uptime
2025-06-09 01:25:44,552 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpw5x0ocy0) - w: [644] 485 bytes/chars
2025-06-09 01:25:44,553 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/status.json' => '../../var/lib/cloud/data/status.json'
2025-06-09 01:25:44,553 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-09 01:25:44,553 - util.py[DEBUG]: Reading 12 bytes from /proc/uptime
2025-06-09 01:25:44,553 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-09 01:25:44,553 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-06-09 01:25:44,553 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,557 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2025-06-09 01:25:44,557 - util.py[DEBUG]: Reading 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2025-06-09 01:25:44,557 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,557 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2025-06-09 01:25:44,557 - util.py[DEBUG]: Reading 811 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2025-06-09 01:25:44,557 - util.py[DEBUG]: Attempting to load yaml from string of length 811 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,558 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-06-09 01:25:44,558 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-06-09 01:25:44,558 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,558 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-installer-network.cfg (quiet=False)
2025-06-09 01:25:44,558 - util.py[DEBUG]: Reading 117 bytes from /etc/cloud/cloud.cfg.d/90-installer-network.cfg
2025-06-09 01:25:44,558 - util.py[DEBUG]: Attempting to load yaml from string of length 117 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,558 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg (quiet=False)
2025-06-09 01:25:44,559 - util.py[DEBUG]: Reading 28 bytes from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg
2025-06-09 01:25:44,559 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,559 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-09 01:25:44,559 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-09 01:25:44,559 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,560 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-09 01:25:44,560 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,560 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-09 01:25:44,561 - log_util.py[DEBUG]: Cloud-init v. 25.1.1-0ubuntu2 running 'init' at Mon, 09 Jun 2025 01:25:44 +0000. Up 12.27 seconds.
2025-06-09 01:25:44,561 - main.py[INFO]: PID [1] started cloud-init 'init'.
2025-06-09 01:25:44,561 - main.py[DEBUG]: No kernel command line url found.
2025-06-09 01:25:44,561 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2025-06-09 01:25:44,561 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 101:4
2025-06-09 01:25:44,561 - util.py[DEBUG]: Reading from /var/lib/cloud/data/python-version (quiet=False)
2025-06-09 01:25:44,561 - util.py[DEBUG]: Reading 4 bytes from /var/lib/cloud/data/python-version
2025-06-09 01:25:44,561 - main.py[DEBUG]: Will wait for network connectivity before continuing
2025-06-09 01:25:44,561 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-06-09 01:25:44,562 - activators.py[DEBUG]: Using selected activator: <class 'cloudinit.net.activators.NetplanActivator'> from priority: ['netplan', 'eni', 'network-manager', 'networkd']
2025-06-09 01:25:44,562 - subp.py[DEBUG]: Running command ['systemctl', 'is-enabled', 'NetworkManager.service'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:44,567 - activators.py[DEBUG]: NetworkManager is enabled, skipping networkd wait
2025-06-09 01:25:44,567 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:44,578 - performance.py[DEBUG]: Running ['ip', '--json', 'addr'] took 0.010 seconds
2025-06-09 01:25:44,578 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:44,580 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2025-06-09 01:25:44,584 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2025-06-09 01:25:44,585 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-06-09 01:25:44,585 - stages.py[DEBUG]: no cache found
2025-06-09 01:25:44,585 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2025-06-09 01:25:44,585 - sources[DEBUG]: Looking for data source in: ['None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2025-06-09 01:25:44,585 - sources[DEBUG]: Searching for network data source in: ['DataSourceNone']
2025-06-09 01:25:44,585 - handlers.py[DEBUG]: start: init-network/search-None: searching for network data from DataSourceNone
2025-06-09 01:25:44,585 - sources[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNone.DataSourceNone'>
2025-06-09 01:25:44,585 - sources[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2025-06-09 01:25:44,585 - sources[DEBUG]: Datasource list set to use a single datasource DataSourceNone.
2025-06-09 01:25:44,586 - util.py[DEBUG]: Reading from /etc/hosts (quiet=False)
2025-06-09 01:25:44,586 - util.py[DEBUG]: Reading 232 bytes from /etc/hosts
2025-06-09 01:25:44,586 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-none - wb: [644] 5 bytes
2025-06-09 01:25:44,586 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-none'
2025-06-09 01:25:44,586 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmp_ojj1a_z) - w: [600] 9908 bytes/chars
2025-06-09 01:25:44,586 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpff7bp132) - w: [644] 1519 bytes/chars
2025-06-09 01:25:44,587 - performance.py[DEBUG]: Getting metadata took 0.002 seconds
2025-06-09 01:25:44,587 - handlers.py[DEBUG]: finish: init-network/search-None: SUCCESS: found network data from DataSourceNone
2025-06-09 01:25:44,587 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-06-09 01:25:44,587 - stages.py[INFO]: Loaded datasource DataSourceNone - DataSourceNone
2025-06-09 01:25:44,587 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-09 01:25:44,587 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-06-09 01:25:44,587 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,594 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2025-06-09 01:25:44,594 - util.py[DEBUG]: Reading 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2025-06-09 01:25:44,594 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,594 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2025-06-09 01:25:44,594 - util.py[DEBUG]: Reading 811 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2025-06-09 01:25:44,594 - util.py[DEBUG]: Attempting to load yaml from string of length 811 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,595 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-06-09 01:25:44,595 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-06-09 01:25:44,595 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,596 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-installer-network.cfg (quiet=False)
2025-06-09 01:25:44,596 - util.py[DEBUG]: Reading 117 bytes from /etc/cloud/cloud.cfg.d/90-installer-network.cfg
2025-06-09 01:25:44,596 - util.py[DEBUG]: Attempting to load yaml from string of length 117 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,596 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg (quiet=False)
2025-06-09 01:25:44,596 - util.py[DEBUG]: Reading 28 bytes from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg
2025-06-09 01:25:44,596 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,596 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-09 01:25:44,597 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-09 01:25:44,597 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,598 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-09 01:25:44,599 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,599 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-09 01:25:44,599 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-06-09 01:25:44,599 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/iid-datasource-none'
2025-06-09 01:25:44,599 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/iid-datasource-none/datasource (quiet=False)
2025-06-09 01:25:44,599 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/datasource - wb: [644] 31 bytes
2025-06-09 01:25:44,600 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 31 bytes
2025-06-09 01:25:44,600 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2025-06-09 01:25:44,600 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2025-06-09 01:25:44,600 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2025-06-09 01:25:44,600 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2025-06-09 01:25:44,600 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2025-06-09 01:25:44,600 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 7236 bytes
2025-06-09 01:25:44,600 - main.py[DEBUG]: [net] init will now be targeting instance id: iid-datasource-none. new=True
2025-06-09 01:25:44,600 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-09 01:25:44,600 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-06-09 01:25:44,600 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,604 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2025-06-09 01:25:44,604 - util.py[DEBUG]: Reading 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2025-06-09 01:25:44,604 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,605 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2025-06-09 01:25:44,605 - util.py[DEBUG]: Reading 811 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2025-06-09 01:25:44,605 - util.py[DEBUG]: Attempting to load yaml from string of length 811 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,605 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-06-09 01:25:44,605 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-06-09 01:25:44,605 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,606 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-installer-network.cfg (quiet=False)
2025-06-09 01:25:44,606 - util.py[DEBUG]: Reading 117 bytes from /etc/cloud/cloud.cfg.d/90-installer-network.cfg
2025-06-09 01:25:44,606 - util.py[DEBUG]: Attempting to load yaml from string of length 117 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,606 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg (quiet=False)
2025-06-09 01:25:44,606 - util.py[DEBUG]: Reading 28 bytes from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg
2025-06-09 01:25:44,606 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,606 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-09 01:25:44,606 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-09 01:25:44,606 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,607 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-09 01:25:44,607 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,608 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-09 01:25:44,608 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2025-06-09 01:25:44,608 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enp0s8/address
2025-06-09 01:25:44,608 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-06-09 01:25:44,608 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-06-09 01:25:44,609 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2025-06-09 01:25:44,609 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enp0s8/address
2025-06-09 01:25:44,609 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-06-09 01:25:44,609 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-06-09 01:25:44,609 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/instance/network-config.json (via temporary file /var/lib/cloud/instance/tmph7la8zw1) - w: [600] 73 bytes/chars
2025-06-09 01:25:44,609 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/network-config.json' => '/var/lib/cloud/instance/network-config.json'
2025-06-09 01:25:44,609 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-network-config-v2.json (quiet=False)
2025-06-09 01:25:44,609 - util.py[DEBUG]: Reading 17906 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-network-config-v2.json
2025-06-09 01:25:44,609 - schema.py[DEBUG]: Validating network-config with netplan API
2025-06-09 01:25:44,610 - util.py[DEBUG]: Writing to /run/cloud-init/tmp/tmpl9u7jso_/etc/netplan/network-config.yaml - wb: [600] 87 bytes
2025-06-09 01:25:44,610 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/addr_assign_type (quiet=False)
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enp0s8/addr_assign_type
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/uevent (quiet=False)
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading 27 bytes from /sys/class/net/enp0s8/uevent
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/address (quiet=False)
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/enp0s8/address
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/device/device (quiet=False)
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading 7 bytes from /sys/class/net/enp0s8/device/device
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/lo/addr_assign_type
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading 23 bytes from /sys/class/net/lo/uevent
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading from /sys/class/net/enp0s8/type (quiet=False)
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/enp0s8/type
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading 4 bytes from /sys/class/net/lo/type
2025-06-09 01:25:44,611 - networking.py[DEBUG]: net: all expected physical devices present
2025-06-09 01:25:44,611 - stages.py[DEBUG]: applying net config names for {'ethernets': {'enp0s8': {'dhcp4': True}}, 'version': 2}
2025-06-09 01:25:44,611 - net[DEBUG]: no interfaces to rename
2025-06-09 01:25:44,611 - stages.py[INFO]: Applying network configuration from system_cfg bringup=True: {'ethernets': {'enp0s8': {'dhcp4': True}}, 'version': 2}
2025-06-09 01:25:44,611 - distros[DEBUG]: Selected renderer 'netplan' from priority list: ['netplan', 'eni', 'sysconfig']
2025-06-09 01:25:44,611 - network_state.py[DEBUG]: Passthrough netplan v2 config
2025-06-09 01:25:44,611 - netplan.py[DEBUG]: V2 to V2 passthrough
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading from /etc/netplan/50-cloud-init.yaml (quiet=False)
2025-06-09 01:25:44,611 - util.py[DEBUG]: Reading 65 bytes from /etc/netplan/50-cloud-init.yaml
2025-06-09 01:25:44,612 - util.py[DEBUG]: Attempting to load yaml from string of length 65 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,612 - util.py[DEBUG]: Attempting to load yaml from string of length 391 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:44,612 - netplan.py[DEBUG]: Rendered netplan config using netplan python API
2025-06-09 01:25:44,612 - netplan.py[DEBUG]: skipping call to `netplan generate`. reason: identical netplan config
2025-06-09 01:25:44,612 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/enp0s8'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:44,618 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/lo'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:44,623 - distros[DEBUG]: Bringing up newly configured network interfaces
2025-06-09 01:25:44,623 - activators.py[DEBUG]: Using selected activator: <class 'cloudinit.net.activators.NetplanActivator'> from priority: ['netplan', 'eni', 'network-manager', 'networkd']
2025-06-09 01:25:44,623 - subp.py[DEBUG]: Running command ['netplan', 'apply'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:45,514 - performance.py[DEBUG]: Running ['netplan', 'apply'] took 0.891 seconds
2025-06-09 01:25:45,515 - activators.py[DEBUG]: Received stderr output: 
** (generate:6093): WARNING **: 01:25:44.707: Permissions for /etc/netplan/01-network-manager-all.yaml are too open. Netplan configuration should NOT be accessible by others.

** (process:6076): WARNING **: 01:25:45.312: Permissions for /etc/netplan/01-network-manager-all.yaml are too open. Netplan configuration should NOT be accessible by others.

** (process:6076): WARNING **: 01:25:45.427: Permissions for /etc/netplan/01-network-manager-all.yaml are too open. Netplan configuration should NOT be accessible by others.

2025-06-09 01:25:45,515 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2025-06-09 01:25:45,515 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2025-06-09 01:25:45,515 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/user-data.txt - wb: [600] 603 bytes
2025-06-09 01:25:45,516 - util.py[DEBUG]: Attempting to load yaml from string of length 603 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:45,518 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/user-data.txt.i - wb: [600] 908 bytes
2025-06-09 01:25:45,518 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/vendor-data.txt - wb: [600] 0 bytes
2025-06-09 01:25:45,518 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/vendor-data.txt.i - wb: [600] 308 bytes
2025-06-09 01:25:45,519 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/vendor-data2.txt - wb: [600] 0 bytes
2025-06-09 01:25:45,519 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/vendor-data2.txt.i - wb: [600] 308 bytes
2025-06-09 01:25:45,519 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/consume_data - wb: [644] 24 bytes
2025-06-09 01:25:45,519 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/consume_data'>)
2025-06-09 01:25:45,519 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2025-06-09 01:25:45,519 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2025-06-09 01:25:45,519 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2025-06-09 01:25:45,519 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2025-06-09 01:25:45,519 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2025-06-09 01:25:45,519 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2025-06-09 01:25:45,519 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2025-06-09 01:25:45,519 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2025-06-09 01:25:45,519 - handlers[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2025-06-09 01:25:45,519 - handlers[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2025-06-09 01:25:45,520 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2025-06-09 01:25:45,520 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2025-06-09 01:25:45,520 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2025-06-09 01:25:45,520 - handlers[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2025-06-09 01:25:45,520 - handlers[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2025-06-09 01:25:45,520 - handlers[DEBUG]: {'MIME-Version': '1.0', 'Content-Type': 'text/cloud-config', 'Content-Disposition': 'attachment; filename="part-001"'}
2025-06-09 01:25:45,520 - handlers[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, part-001, 3) with frequency once-per-instance
2025-06-09 01:25:45,520 - util.py[DEBUG]: Attempting to load yaml from string of length 603 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:45,520 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2025-06-09 01:25:45,520 - handlers[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2025-06-09 01:25:45,522 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/cloud-config.txt - wb: [600] 663 bytes
2025-06-09 01:25:45,522 - handlers[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2025-06-09 01:25:45,522 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2025-06-09 01:25:45,522 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2025-06-09 01:25:45,522 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2025-06-09 01:25:45,522 - handlers[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2025-06-09 01:25:45,522 - handlers[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2025-06-09 01:25:45,522 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2025-06-09 01:25:45,522 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2025-06-09 01:25:45,522 - stages.py[DEBUG]: no vendordata from datasource
2025-06-09 01:25:45,522 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2025-06-09 01:25:45,522 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2025-06-09 01:25:45,522 - stages.py[DEBUG]: no vendordata2 from datasource
2025-06-09 01:25:45,522 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2025-06-09 01:25:45,522 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-09 01:25:45,522 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-06-09 01:25:45,522 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:45,527 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2025-06-09 01:25:45,528 - util.py[DEBUG]: Reading 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2025-06-09 01:25:45,528 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:45,528 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2025-06-09 01:25:45,528 - util.py[DEBUG]: Reading 811 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2025-06-09 01:25:45,528 - util.py[DEBUG]: Attempting to load yaml from string of length 811 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:45,528 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-06-09 01:25:45,528 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-06-09 01:25:45,528 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:45,529 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-installer-network.cfg (quiet=False)
2025-06-09 01:25:45,529 - util.py[DEBUG]: Reading 117 bytes from /etc/cloud/cloud.cfg.d/90-installer-network.cfg
2025-06-09 01:25:45,529 - util.py[DEBUG]: Attempting to load yaml from string of length 117 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:45,529 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg (quiet=False)
2025-06-09 01:25:45,529 - util.py[DEBUG]: Reading 28 bytes from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg
2025-06-09 01:25:45,529 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:45,529 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-09 01:25:45,529 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-09 01:25:45,529 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:45,530 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-09 01:25:45,530 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:45,530 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-09 01:25:45,531 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-09 01:25:45,531 - util.py[DEBUG]: Reading 663 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-09 01:25:45,531 - util.py[DEBUG]: Attempting to load yaml from string of length 663 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:45,532 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/combined-cloud-config.json (via temporary file /run/cloud-init/tmpmcuguofs) - w: [600] 7144 bytes/chars
2025-06-09 01:25:45,532 - util.py[DEBUG]: Reading from /run/cloud-init/instance-data-sensitive.json (quiet=False)
2025-06-09 01:25:45,532 - util.py[DEBUG]: Reading 9908 bytes from /run/cloud-init/instance-data-sensitive.json
2025-06-09 01:25:45,532 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmp4mddrdhq) - w: [600] 12139 bytes/chars
2025-06-09 01:25:45,532 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-09 01:25:45,532 - util.py[DEBUG]: Reading 663 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-09 01:25:45,533 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-06-09 01:25:45,536 - util.py[DEBUG]: Reading 149917 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-06-09 01:25:45,539 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-09 01:25:45,539 - util.py[DEBUG]: Reading 663 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-09 01:25:45,539 - util.py[DEBUG]: Attempting to load yaml from string of length 663 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:45,541 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2025-06-09 01:25:45,541 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 10132 bytes
2025-06-09 01:25:45,542 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2025-06-09 01:25:45,542 - main.py[DEBUG]: no di_report found in config.
2025-06-09 01:25:45,553 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-06-09 01:25:45,554 - modules.py[INFO]: Skipping modules 'bootcmd,disk_setup,update_etc_hosts,ca_certs,rsyslog' because no applicable config is provided.
2025-06-09 01:25:45,554 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2025-06-09 01:25:45,554 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2025-06-09 01:25:45,554 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_seed_random - wb: [644] 23 bytes
2025-06-09 01:25:45,554 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_seed_random'>)
2025-06-09 01:25:45,554 - cc_seed_random.py[DEBUG]: no command provided
2025-06-09 01:25:45,554 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully and took 0.000 seconds
2025-06-09 01:25:45,554 - modules.py[DEBUG]: Running module write_files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2025-06-09 01:25:45,554 - handlers.py[DEBUG]: start: init-network/config-write_files: running config-write_files with frequency once-per-instance
2025-06-09 01:25:45,555 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_write_files - wb: [644] 24 bytes
2025-06-09 01:25:45,555 - helpers.py[DEBUG]: Running config-write_files using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_write_files'>)
2025-06-09 01:25:45,555 - cc_write_files.py[DEBUG]: Skipping module named write_files, no/empty 'write_files' key in configuration
2025-06-09 01:25:45,555 - handlers.py[DEBUG]: finish: init-network/config-write_files: SUCCESS: config-write_files ran successfully and took 0.000 seconds
2025-06-09 01:25:45,555 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2025-06-09 01:25:45,555 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2025-06-09 01:25:45,555 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0xebd817828980>)
2025-06-09 01:25:45,555 - cc_growpart.py[DEBUG]: growpart disabled: mode=off
2025-06-09 01:25:45,555 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully and took 0.000 seconds
2025-06-09 01:25:45,555 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2025-06-09 01:25:45,555 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2025-06-09 01:25:45,555 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0xebd8177c9950>)
2025-06-09 01:25:45,555 - cc_resizefs.py[DEBUG]: Skipping module named resizefs, resizing disabled
2025-06-09 01:25:45,555 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully and took 0.000 seconds
2025-06-09 01:25:45,555 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2025-06-09 01:25:45,555 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2025-06-09 01:25:45,555 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_mounts - wb: [644] 24 bytes
2025-06-09 01:25:45,556 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_mounts'>)
2025-06-09 01:25:45,556 - cc_mounts.py[DEBUG]: mounts configuration is []
2025-06-09 01:25:45,556 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2025-06-09 01:25:45,556 - util.py[DEBUG]: Reading 585 bytes from /etc/fstab
2025-06-09 01:25:45,556 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2025-06-09 01:25:45,556 - cc_mounts.py[DEBUG]: changed ephemeral0 => None
2025-06-09 01:25:45,556 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2025-06-09 01:25:45,556 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2025-06-09 01:25:45,556 - cc_mounts.py[DEBUG]: changed swap => None
2025-06-09 01:25:45,556 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2025-06-09 01:25:45,556 - cc_mounts.py[DEBUG]: no need to setup swap
2025-06-09 01:25:45,556 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2025-06-09 01:25:45,556 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully and took 0.001 seconds
2025-06-09 01:25:45,556 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_hostname.py'>) with frequency once-per-instance
2025-06-09 01:25:45,557 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency once-per-instance
2025-06-09 01:25:45,557 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_set_hostname - wb: [644] 24 bytes
2025-06-09 01:25:45,557 - helpers.py[DEBUG]: Running config-set_hostname using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_set_hostname'>)
2025-06-09 01:25:45,557 - cc_set_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not setting the hostname in module set_hostname
2025-06-09 01:25:45,557 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully and took 0.001 seconds
2025-06-09 01:25:45,557 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2025-06-09 01:25:45,557 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2025-06-09 01:25:45,558 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0xebd8177c91d0>)
2025-06-09 01:25:45,558 - cc_update_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not updating the hostname in module update_hostname
2025-06-09 01:25:45,558 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully and took 0.000 seconds
2025-06-09 01:25:45,558 - modules.py[DEBUG]: Running module users_groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2025-06-09 01:25:45,558 - handlers.py[DEBUG]: start: init-network/config-users_groups: running config-users_groups with frequency once-per-instance
2025-06-09 01:25:45,558 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_users_groups - wb: [644] 23 bytes
2025-06-09 01:25:45,558 - helpers.py[DEBUG]: Running config-users_groups using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_users_groups'>)
2025-06-09 01:25:45,560 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2025-06-09 01:25:45,560 - util.py[DEBUG]: Reading 391 bytes from /etc/os-release
2025-06-09 01:25:45,560 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2025-06-09 01:25:45,560 - util.py[DEBUG]: Reading 0 bytes from /etc/system-image/channel.ini
2025-06-09 01:25:45,561 - distros[DEBUG]: Adding user ralphdaniel
2025-06-09 01:25:45,561 - subp.py[DEBUG]: Running command ['useradd', 'ralphdaniel', '--comment', 'ralphdaniel', '--groups', 'adm,cdrom,dip,lpadmin,plugdev,sudo,users', '--password', 'REDACTED', '--shell', '/bin/bash', '-m'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:45,655 - performance.py[DEBUG]: Running ['useradd', 'ralphdaniel', '--comment', 'ralphdaniel', '--groups', 'adm,cdrom,dip,lpadmin,plugdev,sudo,users', '--password', 'REDACTED', '--shell', '/bin/bash', '-m'] took 0.094 seconds
2025-06-09 01:25:45,655 - subp.py[DEBUG]: Running command ['passwd', '-u', 'ralphdaniel'] with allowed return codes [0, 3] (shell=False, capture=True)
2025-06-09 01:25:45,680 - performance.py[DEBUG]: Running ['passwd', '-u', 'ralphdaniel'] took 0.025 seconds
2025-06-09 01:25:45,680 - handlers.py[DEBUG]: finish: init-network/config-users_groups: SUCCESS: config-users_groups ran successfully and took 0.122 seconds
2025-06-09 01:25:45,680 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2025-06-09 01:25:45,680 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2025-06-09 01:25:45,680 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_ssh - wb: [644] 24 bytes
2025-06-09 01:25:45,680 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_ssh'>)
2025-06-09 01:25:45,680 - util.py[DEBUG]: Reading from /proc/sys/crypto/fips_enabled (quiet=False)
2025-06-09 01:25:45,680 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:45,859 - performance.py[DEBUG]: Running ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] took 0.179 seconds
2025-06-09 01:25:45,859 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:45,862 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:45,866 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_rsa_key.pub (quiet=False)
2025-06-09 01:25:45,866 - util.py[DEBUG]: Reading 576 bytes from /etc/ssh/ssh_host_rsa_key.pub
2025-06-09 01:25:45,866 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2025-06-09 01:25:45,866 - util.py[DEBUG]: Reading 184 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2025-06-09 01:25:45,866 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2025-06-09 01:25:45,866 - util.py[DEBUG]: Reading 104 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2025-06-09 01:25:45,867 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-06-09 01:25:45,867 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2025-06-09 01:25:45,867 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2025-06-09 01:25:45,867 - util.py[DEBUG]: Reading 0 bytes from /root/.ssh/authorized_keys
2025-06-09 01:25:45,867 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-06-09 01:25:45,867 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully and took 0.188 seconds
2025-06-09 01:25:45,867 - modules.py[DEBUG]: Running module set_passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2025-06-09 01:25:45,867 - handlers.py[DEBUG]: start: init-network/config-set_passwords: running config-set_passwords with frequency once-per-instance
2025-06-09 01:25:45,868 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_set_passwords - wb: [644] 24 bytes
2025-06-09 01:25:45,868 - helpers.py[DEBUG]: Running config-set_passwords using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_set_passwords'>)
2025-06-09 01:25:45,868 - cc_set_passwords.py[DEBUG]: Leaving SSH config 'PasswordAuthentication' unchanged. ssh_pwauth=None
2025-06-09 01:25:45,868 - handlers.py[DEBUG]: finish: init-network/config-set_passwords: SUCCESS: config-set_passwords ran successfully and took 0.000 seconds
2025-06-09 01:25:45,868 - main.py[DEBUG]: Ran 10 modules with 0 failures
2025-06-09 01:25:45,868 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-09 01:25:45,868 - util.py[DEBUG]: Reading 12 bytes from /proc/uptime
2025-06-09 01:25:45,868 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmplpvpzwif) - w: [644] 496 bytes/chars
2025-06-09 01:25:45,868 - performance.py[DEBUG]: cloud-init stage: 'init-network' took 1.328 seconds
2025-06-09 01:25:45,868 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2025-06-09 01:25:45,868 - socket.py[INFO]: Sending sd_notify(STATUS=Waiting on external services to complete before starting the config stage.)
2025-06-09 01:25:46,028 - performance.py[DEBUG]: Waiting to start stage config took 0.160 seconds
2025-06-09 01:25:46,029 - socket.py[INFO]: Sending sd_notify(STATUS=Running (config stage))
2025-06-09 01:25:46,029 - signal_handler.py[INFO]: Signal state [<function _handle_exit at 0xebd818c44860>] - previously custom handler.
2025-06-09 01:25:46,031 - signal_handler.py[INFO]: Signal state [<function _handle_exit at 0xebd818c44860>] - previously custom handler.
2025-06-09 01:25:46,031 - signal_handler.py[INFO]: Signal state [<function _handle_exit at 0xebd818c44860>] - previously custom handler.
2025-06-09 01:25:46,031 - handlers.py[DEBUG]: start: modules-config: running modules for config
2025-06-09 01:25:46,033 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-09 01:25:46,033 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-06-09 01:25:46,033 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,042 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2025-06-09 01:25:46,043 - util.py[DEBUG]: Reading 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2025-06-09 01:25:46,043 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,043 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2025-06-09 01:25:46,044 - util.py[DEBUG]: Reading 811 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2025-06-09 01:25:46,044 - util.py[DEBUG]: Attempting to load yaml from string of length 811 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,045 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-06-09 01:25:46,045 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-06-09 01:25:46,045 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,048 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-installer-network.cfg (quiet=False)
2025-06-09 01:25:46,048 - util.py[DEBUG]: Reading 117 bytes from /etc/cloud/cloud.cfg.d/90-installer-network.cfg
2025-06-09 01:25:46,048 - util.py[DEBUG]: Attempting to load yaml from string of length 117 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,049 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg (quiet=False)
2025-06-09 01:25:46,049 - util.py[DEBUG]: Reading 28 bytes from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg
2025-06-09 01:25:46,049 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,049 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-09 01:25:46,049 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-09 01:25:46,050 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,050 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-09 01:25:46,050 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,050 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-09 01:25:46,051 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-09 01:25:46,051 - util.py[DEBUG]: Reading 663 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-09 01:25:46,051 - util.py[DEBUG]: Attempting to load yaml from string of length 663 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,055 - util.py[DEBUG]: Reading from /var/lib/cloud/data/status.json (quiet=False)
2025-06-09 01:25:46,055 - util.py[DEBUG]: Reading 496 bytes from /var/lib/cloud/data/status.json
2025-06-09 01:25:46,055 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-09 01:25:46,055 - util.py[DEBUG]: Reading 12 bytes from /proc/uptime
2025-06-09 01:25:46,055 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpq5wfnrln) - w: [644] 509 bytes/chars
2025-06-09 01:25:46,057 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/status.json' => '../../var/lib/cloud/data/status.json'
2025-06-09 01:25:46,057 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-09 01:25:46,057 - util.py[DEBUG]: Reading 12 bytes from /proc/uptime
2025-06-09 01:25:46,057 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-09 01:25:46,057 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-06-09 01:25:46,057 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,062 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2025-06-09 01:25:46,062 - util.py[DEBUG]: Reading 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2025-06-09 01:25:46,063 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,063 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2025-06-09 01:25:46,063 - util.py[DEBUG]: Reading 811 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2025-06-09 01:25:46,063 - util.py[DEBUG]: Attempting to load yaml from string of length 811 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,064 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-06-09 01:25:46,064 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-06-09 01:25:46,064 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,065 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-installer-network.cfg (quiet=False)
2025-06-09 01:25:46,065 - util.py[DEBUG]: Reading 117 bytes from /etc/cloud/cloud.cfg.d/90-installer-network.cfg
2025-06-09 01:25:46,065 - util.py[DEBUG]: Attempting to load yaml from string of length 117 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,065 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg (quiet=False)
2025-06-09 01:25:46,065 - util.py[DEBUG]: Reading 28 bytes from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg
2025-06-09 01:25:46,065 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,066 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-09 01:25:46,066 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-09 01:25:46,066 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,068 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-09 01:25:46,069 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,069 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-09 01:25:46,069 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-09 01:25:46,069 - util.py[DEBUG]: Reading 663 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-09 01:25:46,069 - util.py[DEBUG]: Attempting to load yaml from string of length 663 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,070 - handlers.py[DEBUG]: start: modules-config/check-cache: attempting to read from cache [trust]
2025-06-09 01:25:46,070 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-06-09 01:25:46,070 - util.py[DEBUG]: Reading 10132 bytes from /var/lib/cloud/instance/obj.pkl
2025-06-09 01:25:46,071 - util.py[DEBUG]: Reading from /run/cloud-init/.instance-id (quiet=False)
2025-06-09 01:25:46,071 - util.py[DEBUG]: Reading 20 bytes from /run/cloud-init/.instance-id
2025-06-09 01:25:46,071 - stages.py[DEBUG]: restored from cache with run check: DataSourceNone
2025-06-09 01:25:46,071 - handlers.py[DEBUG]: finish: modules-config/check-cache: SUCCESS: restored from cache with run check: DataSourceNone
2025-06-09 01:25:46,071 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-09 01:25:46,071 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-06-09 01:25:46,072 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,079 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2025-06-09 01:25:46,080 - util.py[DEBUG]: Reading 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2025-06-09 01:25:46,080 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,080 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2025-06-09 01:25:46,080 - util.py[DEBUG]: Reading 811 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2025-06-09 01:25:46,081 - util.py[DEBUG]: Attempting to load yaml from string of length 811 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,083 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-06-09 01:25:46,083 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-06-09 01:25:46,083 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,085 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-installer-network.cfg (quiet=False)
2025-06-09 01:25:46,085 - util.py[DEBUG]: Reading 117 bytes from /etc/cloud/cloud.cfg.d/90-installer-network.cfg
2025-06-09 01:25:46,085 - util.py[DEBUG]: Attempting to load yaml from string of length 117 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,085 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg (quiet=False)
2025-06-09 01:25:46,085 - util.py[DEBUG]: Reading 28 bytes from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg
2025-06-09 01:25:46,086 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,087 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-09 01:25:46,087 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-09 01:25:46,087 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,090 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-09 01:25:46,090 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,090 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-09 01:25:46,091 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-09 01:25:46,091 - util.py[DEBUG]: Reading 663 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-09 01:25:46,091 - util.py[DEBUG]: Attempting to load yaml from string of length 663 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,093 - log_util.py[DEBUG]: Cloud-init v. 25.1.1-0ubuntu2 running 'modules:config' at Mon, 09 Jun 2025 01:25:46 +0000. Up 13.77 seconds.
2025-06-09 01:25:46,093 - main.py[INFO]: PID [1] started cloud-init 'modules:config'.
2025-06-09 01:25:46,094 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-09 01:25:46,094 - util.py[DEBUG]: Reading 663 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-09 01:25:46,094 - util.py[DEBUG]: Attempting to load yaml from string of length 663 with allowed root types (<class 'dict'>,)
2025-06-09 01:25:46,118 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-06-09 01:25:46,119 - modules.py[INFO]: Skipping modules 'wireguard,snap,ubuntu_autoinstall,keyboard,apt_pipelining,ubuntu_pro,ntp,disable_ec2_metadata,runcmd' because no applicable config is provided.
2025-06-09 01:25:46,119 - modules.py[DEBUG]: Running module ssh_import_id (<module 'cloudinit.config.cc_ssh_import_id' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_import_id.py'>) with frequency once-per-instance
2025-06-09 01:25:46,119 - handlers.py[DEBUG]: start: modules-config/config-ssh_import_id: running config-ssh_import_id with frequency once-per-instance
2025-06-09 01:25:46,119 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_ssh_import_id - wb: [644] 24 bytes
2025-06-09 01:25:46,120 - helpers.py[DEBUG]: Running config-ssh_import_id using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_ssh_import_id'>)
2025-06-09 01:25:46,120 - cc_ssh_import_id.py[DEBUG]: Skipping module named ssh_import_id, no 'ssh_import_id' directives found.
2025-06-09 01:25:46,120 - handlers.py[DEBUG]: finish: modules-config/config-ssh_import_id: SUCCESS: config-ssh_import_id ran successfully and took 0.001 seconds
2025-06-09 01:25:46,120 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2025-06-09 01:25:46,120 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2025-06-09 01:25:46,120 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_locale - wb: [644] 24 bytes
2025-06-09 01:25:46,120 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_locale'>)
2025-06-09 01:25:46,120 - util.py[DEBUG]: Reading from /etc/default/locale (quiet=False)
2025-06-09 01:25:46,120 - util.py[DEBUG]: Reading 13 bytes from /etc/default/locale
2025-06-09 01:25:46,120 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2025-06-09 01:25:46,120 - debian.py[DEBUG]: System locale set to C.UTF-8 via /etc/default/locale
2025-06-09 01:25:46,120 - debian.py[DEBUG]: Generating locales for en_US.UTF-8
2025-06-09 01:25:46,120 - subp.py[DEBUG]: Running command ['locale-gen', 'en_US.UTF-8'] with allowed return codes [0] (shell=False, capture=False)
2025-06-09 01:25:47,344 - performance.py[DEBUG]: Running ['locale-gen', 'en_US.UTF-8'] took 1.224 seconds
2025-06-09 01:25:47,344 - debian.py[DEBUG]: Updating /etc/default/locale with locale setting LANG=en_US.UTF-8
2025-06-09 01:25:47,344 - subp.py[DEBUG]: Running command ['update-locale', '--locale-file=/etc/default/locale', 'LANG=en_US.UTF-8'] with allowed return codes [0] (shell=False, capture=False)
2025-06-09 01:25:47,362 - performance.py[DEBUG]: Running ['update-locale', '--locale-file=/etc/default/locale', 'LANG=en_US.UTF-8'] took 0.019 seconds
2025-06-09 01:25:47,363 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully and took 1.243 seconds
2025-06-09 01:25:47,363 - modules.py[DEBUG]: Running module grub_dpkg (<module 'cloudinit.config.cc_grub_dpkg' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_grub_dpkg.py'>) with frequency once-per-instance
2025-06-09 01:25:47,363 - handlers.py[DEBUG]: start: modules-config/config-grub_dpkg: running config-grub_dpkg with frequency once-per-instance
2025-06-09 01:25:47,363 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_grub_dpkg - wb: [644] 24 bytes
2025-06-09 01:25:47,363 - helpers.py[DEBUG]: Running config-grub_dpkg using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_grub_dpkg'>)
2025-06-09 01:25:47,363 - cc_grub_dpkg.py[DEBUG]: grub_dpkg disabled by config grub_dpkg/enabled=False
2025-06-09 01:25:47,363 - handlers.py[DEBUG]: finish: modules-config/config-grub_dpkg: SUCCESS: config-grub_dpkg ran successfully and took 0.000 seconds
2025-06-09 01:25:47,363 - modules.py[DEBUG]: Running module apt_configure (<module 'cloudinit.config.cc_apt_configure' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_configure.py'>) with frequency once-per-instance
2025-06-09 01:25:47,363 - handlers.py[DEBUG]: start: modules-config/config-apt_configure: running config-apt_configure with frequency once-per-instance
2025-06-09 01:25:47,363 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_apt_configure - wb: [644] 24 bytes
2025-06-09 01:25:47,364 - helpers.py[DEBUG]: Running config-apt_configure using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_apt_configure'>)
2025-06-09 01:25:47,364 - cc_apt_configure.py[DEBUG]: debconf_selections was not set in config
2025-06-09 01:25:47,364 - cc_apt_configure.py[DEBUG]: handling apt config: {'preserve_sources_list': True}
2025-06-09 01:25:47,364 - subp.py[DEBUG]: Running command ['lsb_release', '--all'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:47,383 - performance.py[DEBUG]: Running ['lsb_release', '--all'] took 0.019 seconds
2025-06-09 01:25:47,383 - subp.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:25:47,384 - cc_apt_configure.py[DEBUG]: got primary mirror: None
2025-06-09 01:25:47,384 - cc_apt_configure.py[DEBUG]: got security mirror: None
2025-06-09 01:25:47,384 - util.py[DEBUG]: search for mirror in candidates: '[]'
2025-06-09 01:25:47,384 - util.py[DEBUG]: search for mirror in candidates: '[]'
2025-06-09 01:25:47,384 - distros[DEBUG]: filtered distro mirror info: {'primary': 'http://ports.ubuntu.com/ubuntu-ports', 'security': 'http://ports.ubuntu.com/ubuntu-ports'}
2025-06-09 01:25:47,385 - cc_apt_configure.py[DEBUG]: Apt Mirror info: {'primary': 'http://ports.ubuntu.com/ubuntu-ports', 'security': 'http://ports.ubuntu.com/ubuntu-ports', 'PRIMARY': 'http://ports.ubuntu.com/ubuntu-ports', 'SECURITY': 'http://ports.ubuntu.com/ubuntu-ports', 'MIRROR': 'http://ports.ubuntu.com/ubuntu-ports'}
2025-06-09 01:25:47,385 - handlers.py[DEBUG]: finish: modules-config/config-apt_configure: SUCCESS: config-apt_configure ran successfully and took 0.021 seconds
2025-06-09 01:25:47,385 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2025-06-09 01:25:47,385 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2025-06-09 01:25:47,385 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_timezone - wb: [644] 24 bytes
2025-06-09 01:25:47,385 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_timezone'>)
2025-06-09 01:25:47,387 - util.py[DEBUG]: Writing to /etc/timezone - wb: [644] 12 bytes
2025-06-09 01:25:47,388 - util.py[DEBUG]: Attempting to remove /etc/localtime
2025-06-09 01:25:47,389 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully and took 0.004 seconds
2025-06-09 01:25:47,389 - modules.py[DEBUG]: Running module byobu (<module 'cloudinit.config.cc_byobu' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_byobu.py'>) with frequency once-per-instance
2025-06-09 01:25:47,389 - handlers.py[DEBUG]: start: modules-config/config-byobu: running config-byobu with frequency once-per-instance
2025-06-09 01:25:47,389 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_byobu - wb: [644] 23 bytes
2025-06-09 01:25:47,389 - helpers.py[DEBUG]: Running config-byobu using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_byobu'>)
2025-06-09 01:25:47,389 - cc_byobu.py[DEBUG]: Skipping module named byobu, no 'byobu' values found
2025-06-09 01:25:47,389 - handlers.py[DEBUG]: finish: modules-config/config-byobu: SUCCESS: config-byobu ran successfully and took 0.000 seconds
2025-06-09 01:25:47,389 - main.py[DEBUG]: Ran 6 modules with 0 failures
2025-06-09 01:25:47,389 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-09 01:25:47,389 - util.py[DEBUG]: Reading 12 bytes from /proc/uptime
2025-06-09 01:25:47,390 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpnk2zqihu) - w: [644] 498 bytes/chars
2025-06-09 01:25:47,390 - performance.py[DEBUG]: cloud-init stage: 'modules-config' took 1.359 seconds
2025-06-09 01:25:47,390 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2025-06-09 01:25:47,390 - socket.py[INFO]: Sending sd_notify(STATUS=Waiting on external services to complete before starting the final stage.)
2025-06-09 01:26:04,366 - performance.py[DEBUG]: Waiting to start stage final took 16.975 seconds
2025-06-09 01:26:04,366 - socket.py[INFO]: Sending sd_notify(STATUS=Running (final stage))
2025-06-09 01:26:04,366 - signal_handler.py[INFO]: Signal state [<function _handle_exit at 0xebd818c44860>] - previously custom handler.
2025-06-09 01:26:04,366 - signal_handler.py[INFO]: Signal state [<function _handle_exit at 0xebd818c44860>] - previously custom handler.
2025-06-09 01:26:04,366 - signal_handler.py[INFO]: Signal state [<function _handle_exit at 0xebd818c44860>] - previously custom handler.
2025-06-09 01:26:04,366 - handlers.py[DEBUG]: start: modules-final: running modules for final
2025-06-09 01:26:04,367 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-09 01:26:04,367 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-06-09 01:26:04,367 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,370 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2025-06-09 01:26:04,370 - util.py[DEBUG]: Reading 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2025-06-09 01:26:04,370 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,371 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2025-06-09 01:26:04,371 - util.py[DEBUG]: Reading 811 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2025-06-09 01:26:04,371 - util.py[DEBUG]: Attempting to load yaml from string of length 811 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,371 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-06-09 01:26:04,371 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-06-09 01:26:04,371 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,372 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-installer-network.cfg (quiet=False)
2025-06-09 01:26:04,372 - util.py[DEBUG]: Reading 117 bytes from /etc/cloud/cloud.cfg.d/90-installer-network.cfg
2025-06-09 01:26:04,372 - util.py[DEBUG]: Attempting to load yaml from string of length 117 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,372 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg (quiet=False)
2025-06-09 01:26:04,372 - util.py[DEBUG]: Reading 28 bytes from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg
2025-06-09 01:26:04,372 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,372 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-09 01:26:04,372 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-09 01:26:04,372 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,374 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-09 01:26:04,374 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,374 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-09 01:26:04,374 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-09 01:26:04,374 - util.py[DEBUG]: Reading 663 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-09 01:26:04,374 - util.py[DEBUG]: Attempting to load yaml from string of length 663 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,376 - util.py[DEBUG]: Reading from /var/lib/cloud/data/status.json (quiet=False)
2025-06-09 01:26:04,376 - util.py[DEBUG]: Reading 498 bytes from /var/lib/cloud/data/status.json
2025-06-09 01:26:04,376 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-09 01:26:04,376 - util.py[DEBUG]: Reading 13 bytes from /proc/uptime
2025-06-09 01:26:04,376 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpu04gzgac) - w: [644] 510 bytes/chars
2025-06-09 01:26:04,376 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/status.json' => '../../var/lib/cloud/data/status.json'
2025-06-09 01:26:04,377 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-09 01:26:04,377 - util.py[DEBUG]: Reading 13 bytes from /proc/uptime
2025-06-09 01:26:04,377 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-09 01:26:04,377 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-06-09 01:26:04,377 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,381 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2025-06-09 01:26:04,381 - util.py[DEBUG]: Reading 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2025-06-09 01:26:04,381 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,381 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2025-06-09 01:26:04,381 - util.py[DEBUG]: Reading 811 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2025-06-09 01:26:04,381 - util.py[DEBUG]: Attempting to load yaml from string of length 811 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,382 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-06-09 01:26:04,382 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-06-09 01:26:04,382 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,382 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-installer-network.cfg (quiet=False)
2025-06-09 01:26:04,382 - util.py[DEBUG]: Reading 117 bytes from /etc/cloud/cloud.cfg.d/90-installer-network.cfg
2025-06-09 01:26:04,382 - util.py[DEBUG]: Attempting to load yaml from string of length 117 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,383 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg (quiet=False)
2025-06-09 01:26:04,383 - util.py[DEBUG]: Reading 28 bytes from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg
2025-06-09 01:26:04,383 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,384 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-09 01:26:04,384 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-09 01:26:04,384 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,385 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-09 01:26:04,385 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,385 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-09 01:26:04,385 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-09 01:26:04,385 - util.py[DEBUG]: Reading 663 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-09 01:26:04,385 - util.py[DEBUG]: Attempting to load yaml from string of length 663 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,385 - handlers.py[DEBUG]: start: modules-final/check-cache: attempting to read from cache [trust]
2025-06-09 01:26:04,385 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-06-09 01:26:04,385 - util.py[DEBUG]: Reading 10132 bytes from /var/lib/cloud/instance/obj.pkl
2025-06-09 01:26:04,386 - util.py[DEBUG]: Reading from /run/cloud-init/.instance-id (quiet=False)
2025-06-09 01:26:04,386 - util.py[DEBUG]: Reading 20 bytes from /run/cloud-init/.instance-id
2025-06-09 01:26:04,386 - stages.py[DEBUG]: restored from cache with run check: DataSourceNone
2025-06-09 01:26:04,386 - handlers.py[DEBUG]: finish: modules-final/check-cache: SUCCESS: restored from cache with run check: DataSourceNone
2025-06-09 01:26:04,386 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-06-09 01:26:04,386 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-06-09 01:26:04,386 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,390 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2025-06-09 01:26:04,390 - util.py[DEBUG]: Reading 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2025-06-09 01:26:04,390 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,390 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2025-06-09 01:26:04,390 - util.py[DEBUG]: Reading 811 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2025-06-09 01:26:04,390 - util.py[DEBUG]: Attempting to load yaml from string of length 811 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,391 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-06-09 01:26:04,391 - util.py[DEBUG]: Reading 343 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-06-09 01:26:04,391 - util.py[DEBUG]: Attempting to load yaml from string of length 343 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,392 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-installer-network.cfg (quiet=False)
2025-06-09 01:26:04,392 - util.py[DEBUG]: Reading 117 bytes from /etc/cloud/cloud.cfg.d/90-installer-network.cfg
2025-06-09 01:26:04,392 - util.py[DEBUG]: Attempting to load yaml from string of length 117 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,393 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg (quiet=False)
2025-06-09 01:26:04,393 - util.py[DEBUG]: Reading 28 bytes from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg
2025-06-09 01:26:04,393 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,393 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-06-09 01:26:04,393 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-06-09 01:26:04,393 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,394 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-06-09 01:26:04,394 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,394 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-06-09 01:26:04,394 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-09 01:26:04,394 - util.py[DEBUG]: Reading 663 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-09 01:26:04,394 - util.py[DEBUG]: Attempting to load yaml from string of length 663 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,396 - log_util.py[DEBUG]: Cloud-init v. 25.1.1-0ubuntu2 running 'modules:final' at Mon, 09 Jun 2025 01:26:04 +0000. Up 32.09 seconds.
2025-06-09 01:26:04,396 - main.py[INFO]: PID [1] started cloud-init 'modules:final'.
2025-06-09 01:26:04,396 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-06-09 01:26:04,396 - util.py[DEBUG]: Reading 663 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-06-09 01:26:04,396 - util.py[DEBUG]: Attempting to load yaml from string of length 663 with allowed root types (<class 'dict'>,)
2025-06-09 01:26:04,426 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-06-09 01:26:04,429 - modules.py[INFO]: Skipping modules 'package_update_upgrade_install,fan,landscape,lxd,ubuntu_drivers,puppet,chef,ansible,mcollective,salt_minion,phone_home,power_state_change' because no applicable config is provided.
2025-06-09 01:26:04,430 - modules.py[DEBUG]: Running module write_files_deferred (<module 'cloudinit.config.cc_write_files_deferred' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_write_files_deferred.py'>) with frequency once-per-instance
2025-06-09 01:26:04,432 - handlers.py[DEBUG]: start: modules-final/config-write_files_deferred: running config-write_files_deferred with frequency once-per-instance
2025-06-09 01:26:04,432 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_write_files_deferred - wb: [644] 24 bytes
2025-06-09 01:26:04,432 - helpers.py[DEBUG]: Running config-write_files_deferred using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_write_files_deferred'>)
2025-06-09 01:26:04,432 - util.py[DEBUG]: Writing to /etc/cloud/cloud-init.disabled - wb: [644] 132 bytes
2025-06-09 01:26:04,432 - util.py[DEBUG]: Changing the ownership of /etc/cloud/cloud-init.disabled to 0:0
2025-06-09 01:26:04,432 - handlers.py[DEBUG]: finish: modules-final/config-write_files_deferred: SUCCESS: config-write_files_deferred ran successfully and took 0.000 seconds
2025-06-09 01:26:04,432 - modules.py[DEBUG]: Running module reset_rmc (<module 'cloudinit.config.cc_reset_rmc' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_reset_rmc.py'>) with frequency once-per-instance
2025-06-09 01:26:04,432 - handlers.py[DEBUG]: start: modules-final/config-reset_rmc: running config-reset_rmc with frequency once-per-instance
2025-06-09 01:26:04,432 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_reset_rmc - wb: [644] 24 bytes
2025-06-09 01:26:04,433 - helpers.py[DEBUG]: Running config-reset_rmc using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_reset_rmc'>)
2025-06-09 01:26:04,433 - cc_reset_rmc.py[DEBUG]: Skipping creation of new ct_node_id node
2025-06-09 01:26:04,434 - handlers.py[DEBUG]: finish: modules-final/config-reset_rmc: SUCCESS: config-reset_rmc ran successfully and took 0.000 seconds
2025-06-09 01:26:04,439 - modules.py[DEBUG]: Running module scripts_vendor (<module 'cloudinit.config.cc_scripts_vendor' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_vendor.py'>) with frequency once-per-instance
2025-06-09 01:26:04,440 - handlers.py[DEBUG]: start: modules-final/config-scripts_vendor: running config-scripts_vendor with frequency once-per-instance
2025-06-09 01:26:04,440 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_vendor - wb: [644] 24 bytes
2025-06-09 01:26:04,442 - helpers.py[DEBUG]: Running config-scripts_vendor using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_vendor'>)
2025-06-09 01:26:04,443 - handlers.py[DEBUG]: finish: modules-final/config-scripts_vendor: SUCCESS: config-scripts_vendor ran successfully and took 0.002 seconds
2025-06-09 01:26:04,443 - modules.py[DEBUG]: Running module scripts_per_once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_once.py'>) with frequency once
2025-06-09 01:26:04,444 - handlers.py[DEBUG]: start: modules-final/config-scripts_per_once: running config-scripts_per_once with frequency once
2025-06-09 01:26:04,444 - util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 24 bytes
2025-06-09 01:26:04,445 - helpers.py[DEBUG]: Running config-scripts_per_once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
2025-06-09 01:26:04,445 - handlers.py[DEBUG]: finish: modules-final/config-scripts_per_once: SUCCESS: config-scripts_per_once ran successfully and took 0.001 seconds
2025-06-09 01:26:04,445 - modules.py[DEBUG]: Running module scripts_per_boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_boot.py'>) with frequency always
2025-06-09 01:26:04,445 - handlers.py[DEBUG]: start: modules-final/config-scripts_per_boot: running config-scripts_per_boot with frequency always
2025-06-09 01:26:04,445 - helpers.py[DEBUG]: Running config-scripts_per_boot using lock (<cloudinit.helpers.DummyLock object at 0xebd8177d62c0>)
2025-06-09 01:26:04,445 - handlers.py[DEBUG]: finish: modules-final/config-scripts_per_boot: SUCCESS: config-scripts_per_boot ran successfully and took 0.000 seconds
2025-06-09 01:26:04,445 - modules.py[DEBUG]: Running module scripts_per_instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_instance.py'>) with frequency once-per-instance
2025-06-09 01:26:04,445 - handlers.py[DEBUG]: start: modules-final/config-scripts_per_instance: running config-scripts_per_instance with frequency once-per-instance
2025-06-09 01:26:04,445 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_per_instance - wb: [644] 24 bytes
2025-06-09 01:26:04,445 - helpers.py[DEBUG]: Running config-scripts_per_instance using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_per_instance'>)
2025-06-09 01:26:04,445 - handlers.py[DEBUG]: finish: modules-final/config-scripts_per_instance: SUCCESS: config-scripts_per_instance ran successfully and took 0.000 seconds
2025-06-09 01:26:04,445 - modules.py[DEBUG]: Running module scripts_user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) with frequency once-per-instance
2025-06-09 01:26:04,445 - handlers.py[DEBUG]: start: modules-final/config-scripts_user: running config-scripts_user with frequency once-per-instance
2025-06-09 01:26:04,445 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_user - wb: [644] 23 bytes
2025-06-09 01:26:04,445 - helpers.py[DEBUG]: Running config-scripts_user using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_user'>)
2025-06-09 01:26:04,446 - handlers.py[DEBUG]: finish: modules-final/config-scripts_user: SUCCESS: config-scripts_user ran successfully and took 0.001 seconds
2025-06-09 01:26:04,446 - modules.py[DEBUG]: Running module ssh_authkey_fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) with frequency once-per-instance
2025-06-09 01:26:04,446 - handlers.py[DEBUG]: start: modules-final/config-ssh_authkey_fingerprints: running config-ssh_authkey_fingerprints with frequency once-per-instance
2025-06-09 01:26:04,446 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_ssh_authkey_fingerprints - wb: [644] 24 bytes
2025-06-09 01:26:04,446 - helpers.py[DEBUG]: Running config-ssh_authkey_fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_ssh_authkey_fingerprints'>)
2025-06-09 01:26:04,446 - util.py[DEBUG]: Changing the ownership of /home/ralphdaniel/.ssh to 1000:1000
2025-06-09 01:26:04,446 - util.py[DEBUG]: Writing to /home/ralphdaniel/.ssh/authorized_keys - wb: [600] 0 bytes
2025-06-09 01:26:04,448 - util.py[DEBUG]: Changing the ownership of /home/ralphdaniel/.ssh/authorized_keys to 1000:1000
2025-06-09 01:26:04,448 - util.py[DEBUG]: Reading from /home/ralphdaniel/.ssh/authorized_keys (quiet=False)
2025-06-09 01:26:04,448 - util.py[DEBUG]: Reading 0 bytes from /home/ralphdaniel/.ssh/authorized_keys
2025-06-09 01:26:04,448 - handlers.py[DEBUG]: finish: modules-final/config-ssh_authkey_fingerprints: SUCCESS: config-ssh_authkey_fingerprints ran successfully and took 0.002 seconds
2025-06-09 01:26:04,448 - modules.py[DEBUG]: Running module keys_to_console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_keys_to_console.py'>) with frequency once-per-instance
2025-06-09 01:26:04,448 - handlers.py[DEBUG]: start: modules-final/config-keys_to_console: running config-keys_to_console with frequency once-per-instance
2025-06-09 01:26:04,448 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_keys_to_console - wb: [644] 24 bytes
2025-06-09 01:26:04,448 - helpers.py[DEBUG]: Running config-keys_to_console using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_keys_to_console'>)
2025-06-09 01:26:04,448 - subp.py[DEBUG]: Running command ['/usr/lib/cloud-init/write-ssh-key-fingerprints', '', ''] with allowed return codes [0] (shell=False, capture=True)
2025-06-09 01:26:04,483 - performance.py[DEBUG]: Running ['/usr/lib/cloud-init/write-ssh-key-fingerprints', '', ''] took 0.035 seconds
2025-06-09 01:26:04,484 - handlers.py[DEBUG]: finish: modules-final/config-keys_to_console: SUCCESS: config-keys_to_console ran successfully and took 0.036 seconds
2025-06-09 01:26:04,484 - modules.py[DEBUG]: Running module install_hotplug (<module 'cloudinit.config.cc_install_hotplug' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_install_hotplug.py'>) with frequency once-per-instance
2025-06-09 01:26:04,484 - handlers.py[DEBUG]: start: modules-final/config-install_hotplug: running config-install_hotplug with frequency once-per-instance
2025-06-09 01:26:04,484 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_install_hotplug - wb: [644] 23 bytes
2025-06-09 01:26:04,484 - helpers.py[DEBUG]: Running config-install_hotplug using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_install_hotplug'>)
2025-06-09 01:26:04,484 - util.py[DEBUG]: Reading from /var/lib/cloud/hotplug.enabled (quiet=False)
2025-06-09 01:26:04,484 - util.py[DEBUG]: File not found: /var/lib/cloud/hotplug.enabled
2025-06-09 01:26:04,484 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>}}
2025-06-09 01:26:04,484 - stages.py[DEBUG]: Event Denied: scopes=['network'] EventType=hotplug
2025-06-09 01:26:04,484 - cc_install_hotplug.py[DEBUG]: Skipping hotplug install, not enabled
2025-06-09 01:26:04,484 - handlers.py[DEBUG]: finish: modules-final/config-install_hotplug: SUCCESS: config-install_hotplug ran successfully and took 0.001 seconds
2025-06-09 01:26:04,484 - modules.py[DEBUG]: Running module final_message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2025-06-09 01:26:04,484 - handlers.py[DEBUG]: start: modules-final/config-final_message: running config-final_message with frequency always
2025-06-09 01:26:04,484 - helpers.py[DEBUG]: Running config-final_message using lock (<cloudinit.helpers.DummyLock object at 0xebd8177d63f0>)
2025-06-09 01:26:04,484 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-09 01:26:04,485 - util.py[DEBUG]: Reading 13 bytes from /proc/uptime
2025-06-09 01:26:04,488 - log_util.py[DEBUG]: Cloud-init v. 25.1.1-0ubuntu2 finished at Mon, 09 Jun 2025 01:26:04 +0000. Datasource DataSourceNone.  Up 32.20 seconds
2025-06-09 01:26:04,488 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 61 bytes
2025-06-09 01:26:04,488 - handlers.py[DEBUG]: finish: modules-final/config-final_message: SUCCESS: config-final_message ran successfully and took 0.004 seconds
2025-06-09 01:26:04,489 - main.py[DEBUG]: Ran 11 modules with 0 failures
2025-06-09 01:26:04,489 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-06-09 01:26:04,489 - util.py[DEBUG]: Reading 13 bytes from /proc/uptime
2025-06-09 01:26:04,489 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpxgbvgtvt) - w: [644] 500 bytes/chars
2025-06-09 01:26:04,489 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpxqkfnkzp) - w: [644] 65 bytes/chars
2025-06-09 01:26:04,489 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2025-06-09 01:26:04,489 - performance.py[DEBUG]: cloud-init stage: 'modules-final' took 0.123 seconds
2025-06-09 01:26:04,489 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
2025-06-09 01:26:04,489 - socket.py[INFO]: Sending sd_notify(STATUS=Completed)
2025-06-09 01:26:04,490 - socket.py[INFO]: Sending sd_notify(STOPPING=1)
